Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -83,24 +83,22 @@ jobs:
           source .venv/bin/activate  # Activate virtual environment
           p4a create --requirements=$(paste -s -d, pipgrip.lock) --arch arm64-v8a --arch armeabi-v7a --arch x86_64 --sdk-dir $ANDROID_SDK_ROOT --ndk-dir $ANDROID_NDK_HOME --dist-name mydist
 
-      - name: Build WHL package
+      - name: Copy WHL file
         run: |
-          cd /home/runner/.local/share/python-for-android/dists/mydist
-          python3 setup.py bdist_wheel
-
-      - name: List files in dist directory
-        run: |
-          ls -l /home/runner/.local/share/python-for-android/dists/mydist/dist/
-          
-      - name: Rename and move the wheel file
-        run: |
+          # Assuming the WHL file is generated in the following directory
+          WHL_DIR="/home/runner/.local/share/python-for-android/dists/mydist/dist/"
           PACKAGE_NAME=$(head -n 1 requirements.txt | cut -d'=' -f1)
           PACKAGE_VERSION=$(head -n 1 requirements.txt | grep -oP '(?<===)[\d.]+')
-          
-          if [ -z "$PACKAGE_VERSION" ]; then
-            mv /home/runner/.local/share/python-for-android/dists/mydist/dist/*.whl /home/runner/.local/share/python-for-android/dists/${PACKAGE_NAME}-yassen-py3-none-any.whl
+
+          if [ -d "$WHL_DIR" ]; then
+            if [ -z "$PACKAGE_VERSION" ]; then
+              mv "$WHL_DIR"*.whl "/home/runner/.local/share/python-for-android/dists/${PACKAGE_NAME}-yassen-py3-none-any.whl"
+            else
+              mv "$WHL_DIR"*.whl "/home/runner/.local/share/python-for-android/dists/${PACKAGE_NAME}-${PACKAGE_VERSION}-yassen-py3-none-any.whl"
+            fi
           else
-            mv /home/runner/.local/share/python-for-android/dists/mydist/dist/*.whl /home/runner/.local/share/python-for-android/dists/${PACKAGE_NAME}-${PACKAGE_VERSION}-yassen-py3-none-any.whl
+            echo "WHL directory not found!"
+            exit 1
           fi
 
       - name: Upload WHL artifact
