Update python-package.yml

diff --git a/.github/workflows/python-package.yml b/.github/workflows/python-package.yml
--- a/.github/workflows/python-package.yml
+++ b/.github/workflows/python-package.yml
@@ -24,12 +24,19 @@ jobs:
         with:
           python-version: '3.x'
 
+      - name: Upload requirements.txt
+        run: |
+          if [ ! -f requirements.txt ]; then
+            echo "requirements.txt not found!"
+            exit 1
+          fi
+          cat requirements.txt
+
       - name: Install Dependencies
         run: |
           sudo apt-get update
           sudo apt-get install -y gettext
-          sudo apt-get install -y libiconv-hook-dev autoconf automake libtool pkg-config  # إضافة pkg-config
-          sudo apt-get install -y ccache
+          sudo apt-get install -y libiconv-hook-dev autoconf automake
 
       - name: Install Python Dependencies
         run: |
@@ -37,6 +44,7 @@ jobs:
           source .venv/bin/activate
           pip install --upgrade pip
           pip install maturin
+          # استخدام GITHUB_TOKEN للمصادقة
           git config --global url."https://${{ secrets.GITHUB_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
           pip install git+https://github.com/kivy/python-for-android.git@develop || pip install python-for-android
           pip install --upgrade cython pipgrip
@@ -74,7 +82,7 @@ jobs:
         id: build_package
         run: |
           source .venv/bin/activate  # Activate virtual environment
-          p4a create --requirements=$(paste -s -d, pipgrip.lock) --arch arm64-v8a --arch armeabi-v7a --arch x86_64 --sdk-dir $ANDROID_SDK_ROOT --ndk-dir $ANDROID_NDK_HOME --ndk-api 24 --dist-name mydist
+          p4a create --requirements=$(paste -s -d, pipgrip.lock) --arch arm64-v8a --arch armeabi-v7a --arch x86_64 --sdk-dir $ANDROID_SDK_ROOT --ndk-dir $ANDROID_NDK_HOME --dist-name mydist
 
       - name: Zip mydist folder
         run: |
